sonar.projectKey=zomato
sonar.projectName=zomato
sonar.sources=src
sonar.sourceEncoding=UTF-8
sonar.tests=src
sonar.test.inclusions=**/*.test.js,**/*.test.jsx
sonar.exclusions=**/node_modules/**,**/coverage/**
sonar.coverage.exclusions=**/node_modules/**,**/coverage/**,**/__tests__/**,**/*.test.js,**/*.test.jsx
sonar.javascript.lcov.reportPaths=coverage/lcov.info
