sonar.projectKey=zomato
sonar.projectName=zomato
sonar.sources=src
sonar.sourceEncoding=UTF-8
sonar.tests=src
sonar.test.inclusions=**/*.test.js,**/*.test.jsx,**/__tests__/**/*.js,**/__tests__/**/*.jsx
sonar.test.exclusions=**/setupTests.js,**/reportWebVitals.js
sonar.exclusions=**/setupTests.js,**/reportWebVitals.js,coverage/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info
