sonar.projectKey=zomato-clone-backend
sonar.projectName=Zomato Clone Backend
sonar.projectVersion=1.0.0
sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*.test.ts,**/*.spec.ts,**/__tests__/**
sonar.exclusions=**/node_modules/**,**/dist/**,**/coverage/**,**/*.min.js,**/migrations/**,**/seeds/**,**/*.d.ts
sonar.coverage.exclusions=**/*.test.ts,**/*.spec.ts,**/migrations/**,**/seeds/**,**/index.ts
sonar.cpd.exclusions=**/migrations/**,**/seeds/**
sonar.typescript.lcov.reportPaths=coverage/lcov.info
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.sourceEncoding=UTF-8
sonar.qualitygate.wait=false
sonar.scm.provider=git
sonar.coverage.minimum=0
sonar.duplicated_lines_density.maximum=10
sonar.maintainability_rating.maximum=B
sonar.reliability_rating.maximum=B
sonar.security_rating.maximum=B
sonar.security_hotspots_reviewed.minimum=0
